database:
  host: "localhost"
  port: 5432
  user: "ridwanclouds"
  password: "your_password"
  database: "goalbet"

data_sources:
  - url: "https://www.football-data.co.uk/mmz4281/1920/E0.csv"
  - url: "https://www.football-data.co.uk/mmz4281/1920/E2.csv"
  - url: "https://www.football-data.co.uk/mmz4281/0203/E1.csv"

staging_paths:
  raw_data: "./data/raw/"
  transformed_data: "./data/transformed/"
